# Generated by Django 4.2.17 on 2025-01-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News Article', 'verbose_name_plural': 'News Articles'},
        ),
    ]
