# Generated by Django 4.2.17 on 2025-01-04 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='read_later_by',
            field=models.ManyToManyField(blank=True, related_name='read_later_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
