# Generated by Django 4.2.17 on 2025-01-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_userprofile_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='posted_news',
        ),
    ]
