# Generated by Django 4.2.18 on 2025-01-27 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0009_alter_organization_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='read_later',
        ),
        migrations.CreateModel(
            name='ReadLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later', to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_later', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
