# Generated by Django 4.2.18 on 2025-01-30 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0010_remove_news_read_later_readlater'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('foundation', models.DateField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='readlater',
            name='news_article',
        ),
        migrations.RemoveField(
            model_name='readlater',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='affiliation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to='news.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='ReadLater',
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='news.userprofile'),
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to='news.userprofile'),
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like', to='news.userprofile'),
        ),
        migrations.AddField(
            model_name='newsarticles',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='news.organizations'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news_article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='news.newsarticles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='affiliated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliated_users', to='news.organizations'),
        ),
    ]
