# Generated by Django 4.2.18 on 2025-01-31 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsarticles_organizations_remove_news_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.newsarticles'),
        ),
    ]
