# Generated by Django 4.2.18 on 2025-02-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_comment_news_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
