# Generated by Django 4.2.18 on 2025-02-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_remove_userprofile_subscriber_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organization_images/'),
        ),
    ]
