# Generated by Django 4.2.18 on 2025-02-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_organizations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_articles_images/'),
        ),
    ]
