# Generated by Django 4.2.18 on 2025-02-02 13:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_newsarticles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
